import {
  useEffect,
  useState,
} from "react";

import {
  ArrowRight,
  BrainCircuit,
  CheckCircle2,
  Eye,
  EyeOff,
  LockKeyhole,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

import {
  Navigate,
  useLocation,
  useNavigate,
} from "react-router-dom";

import { useAuth } from "../context/AuthContext";

function LoginPage() {
  const {
    login,
    isAuthenticated,
  } = useAuth();

  const navigate = useNavigate();
  const location = useLocation();

  const demoEmail =
    import.meta.env.VITE_DEMO_EMAIL ||
    "";

  const demoPassword =
    import.meta.env.VITE_DEMO_PASSWORD ||
    "";

  const [email, setEmail] =
    useState("");

  const [password, setPassword] =
    useState("");

  const [showPassword, setShowPassword] =
    useState(false);

  const [loading, setLoading] =
    useState(false);

  const [error, setError] =
    useState("");

  const destination =
    location.state?.from ||
    "/dashboard";

  useEffect(() => {
    setError("");
  }, [email, password]);

  if (isAuthenticated) {
    return (
      <Navigate
        to="/dashboard"
        replace
      />
    );
  }

  const handleSubmit = async (
    event,
  ) => {
    event.preventDefault();

    if (!email.trim()) {
      setError(
        "Please enter your email address.",
      );
      return;
    }

    if (!password) {
      setError(
        "Please enter your password.",
      );
      return;
    }

    setLoading(true);
    setError("");

    try {
      await login(
        email.trim(),
        password,
      );

      navigate(destination, {
        replace: true,
      });
    } catch (requestError) {
      setError(
        requestError.response?.data
          ?.message ||
          "Unable to sign in. Check that the backend is running.",
      );
    } finally {
      setLoading(false);
    }
  };

  const fillDemoCredentials = () => {
    setEmail(demoEmail);
    setPassword(demoPassword);
  };

  return (
    <div className="min-h-screen bg-slate-950 lg:grid lg:grid-cols-[1.08fr_0.92fr]">
      <section className="relative hidden min-h-screen overflow-hidden bg-slate-950 px-14 py-12 text-white lg:flex lg:flex-col">
        <div className="absolute -left-40 top-24 h-96 w-96 rounded-full bg-cyan-500/10 blur-3xl" />
        <div className="absolute -bottom-40 right-0 h-[32rem] w-[32rem] rounded-full bg-blue-500/10 blur-3xl" />

        <div className="relative z-10 flex items-center gap-3">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-slate-950">
            <BrainCircuit
              size={24}
              strokeWidth={2}
            />
          </div>

          <div>
            <div className="text-lg font-bold tracking-[0.12em]">
              UNDER RIGHT
            </div>

            <div className="text-xs text-slate-400">
              Credit Intelligence
            </div>
          </div>
        </div>

        <div className="relative z-10 my-auto max-w-2xl">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-slate-700 bg-slate-900/80 px-4 py-2 text-sm text-slate-300">
            <Sparkles
              size={15}
              className="text-cyan-300"
            />

            Explainable AI-Powered Credit Intelligence
          </div>

          <h1 className="max-w-xl text-5xl font-semibold leading-[1.12] tracking-tight">
            Better context for
            human credit decisions.
          </h1>

          <p className="mt-6 max-w-xl text-lg leading-8 text-slate-400">
            UnderRight combines
            transparent deterministic
            scoring with AI-assisted
            explanations so underwriters
            can understand the signals
            behind every assessment.
          </p>

          <div className="mt-12 grid gap-5">
            <Feature
              icon={ShieldCheck}
              title="Transparent scoring"
              description="Every score is generated by configurable prototype rules, not an LLM."
            />

            <Feature
              icon={BrainCircuit}
              title="AI for explanation"
              description="Gemini explains supplied factors but cannot modify the numerical assessment."
            />

            <Feature
              icon={CheckCircle2}
              title="Human controlled"
              description="UnderRight supports underwriting review. It does not approve or reject credit."
            />
          </div>
        </div>

        <p className="relative z-10 text-xs leading-5 text-slate-500">
          Hackathon prototype using
          synthetic demonstration data.
          Not intended for production
          lending decisions.
        </p>
      </section>

      <section className="flex min-h-screen items-center justify-center bg-slate-50 px-5 py-10 sm:px-8">
        <div className="w-full max-w-md">
          <div className="mb-8 flex items-center gap-3 lg:hidden">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-white">
              <BrainCircuit size={21} />
            </div>

            <div>
              <div className="font-bold tracking-[0.1em] text-slate-950">
                UNDER RIGHT
              </div>

              <div className="text-xs text-slate-500">
                Credit Intelligence
              </div>
            </div>
          </div>

          <div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-[0_18px_55px_rgba(15,23,42,0.07)] sm:p-9">
            <div>
              <p className="text-sm font-semibold text-cyan-700">
                UNDERWRITER PORTAL
              </p>

              <h2 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">
                Welcome back
              </h2>

              <p className="mt-2 text-sm leading-6 text-slate-500">
                Sign in to review credit
                intelligence assessments.
              </p>
            </div>

            <form
              onSubmit={handleSubmit}
              className="mt-8"
            >
              <div>
                <label
                  htmlFor="email"
                  className="mb-2 block text-sm font-medium text-slate-700"
                >
                  Email address
                </label>

                <input
                  id="email"
                  type="email"
                  autoComplete="email"
                  value={email}
                  onChange={(event) =>
                    setEmail(
                      event.target.value,
                    )
                  }
                  placeholder="underwriter@example.com"
                  className="h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm text-slate-950 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-4 focus:ring-slate-100"
                />
              </div>

              <div className="mt-5">
                <label
                  htmlFor="password"
                  className="mb-2 block text-sm font-medium text-slate-700"
                >
                  Password
                </label>

                <div className="relative">
                  <LockKeyhole
                    size={17}
                    className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
                  />

                  <input
                    id="password"
                    type={
                      showPassword
                        ? "text"
                        : "password"
                    }
                    autoComplete="current-password"
                    value={password}
                    onChange={(
                      event,
                    ) =>
                      setPassword(
                        event.target
                          .value,
                      )
                    }
                    placeholder="Enter password"
                    className="h-12 w-full rounded-xl border border-slate-300 bg-white pl-11 pr-12 text-sm text-slate-950 outline-none transition placeholder:text-slate-400 focus:border-slate-500 focus:ring-4 focus:ring-slate-100"
                  />

                  <button
                    type="button"
                    onClick={() =>
                      setShowPassword(
                        (current) =>
                          !current,
                      )
                    }
                    className="absolute right-3 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"
                    aria-label="Toggle password visibility"
                  >
                    {showPassword ? (
                      <EyeOff
                        size={17}
                      />
                    ) : (
                      <Eye
                        size={17}
                      />
                    )}
                  </button>
                </div>
              </div>

              {error && (
                <div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm leading-5 text-red-700">
                  {error}
                </div>
              )}

              <button
                type="submit"
                disabled={loading}
                className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {loading
                  ? "Signing in..."
                  : "Sign in"}

                {!loading && (
                  <ArrowRight
                    size={17}
                  />
                )}
              </button>
            </form>

            <div className="mt-7 rounded-2xl border border-cyan-100 bg-cyan-50/70 p-4">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs font-bold tracking-wide text-cyan-800">
                    DEMO ACCOUNT
                  </p>

                  <p className="mt-1 text-xs text-slate-600">
                    Use these credentials
                    for the hackathon demo.
                  </p>
                </div>

                <button
                  type="button"
                  onClick={
                    fillDemoCredentials
                  }
                  className="shrink-0 rounded-lg border border-cyan-200 bg-white px-3 py-2 text-xs font-semibold text-cyan-800 transition hover:bg-cyan-50"
                >
                  Fill credentials
                </button>
              </div>

              <div className="mt-4 space-y-2 rounded-xl bg-white/80 p-3 font-mono text-xs text-slate-700">
                <div>
                  <span className="text-slate-400">
                    Email:
                  </span>{" "}
                  {demoEmail ||
                    "Not configured"}
                </div>

                <div>
                  <span className="text-slate-400">
                    Password:
                  </span>{" "}
                  {demoPassword
                    ? "••••••••••••••"
                    : "Not configured"}
                </div>
              </div>
            </div>
          </div>

          <p className="mt-5 text-center text-xs leading-5 text-slate-400">
            Prototype decision-support
            environment. Final lending
            decisions remain with an
            authorized human process.
          </p>
        </div>
      </section>
    </div>
  );
}

function Feature({
  icon: Icon,
  title,
  description,
}) {
  return (
    <div className="flex gap-4">
      <div className="mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-700 bg-slate-900 text-cyan-300">
        <Icon size={19} />
      </div>

      <div>
        <h3 className="font-medium text-slate-100">
          {title}
        </h3>

        <p className="mt-1 max-w-md text-sm leading-6 text-slate-400">
          {description}
        </p>
      </div>
    </div>
  );
}

export default LoginPage;